apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsec
  labels:
    app: parsec
spec:
  replicas: 6
  selector:
    matchLabels:
      app: parsec
  template:
    metadata:
      name: parsec
      labels:
        app: parsec
    spec:
      containers:

      - name: parsec
        imagePullPolicy: Always
        image: aorfanou/parsec
        tty: true
        securityContext:
          privileged: true
        args:
        - "-a run"
        - "-i native"
        - "-S parsec"
        - "-n 1"
        - "-s 1m"
        - "-p facesim,ferret,fluidanimate,streamcluster"
