runner: !AllocationRunner
  measurement_runner: !MeasurementRunner
    interval: 10.0
    node: !KubernetesNode
      cgroup_driver: cgroupfs
      monitored_namespaces: ["kro", "prometheus", "grafana", "wca"]
      kubeapi_host: !Env KUBERNETES_SERVICE_HOST
      kubeapi_port: !Env KUBERNETES_SERVICE_PORT
      node_ip: !Env HOST_IP
  
    metrics_storage: !LogStorage
      overwrite: True
      output_filename: /var/lib/wca/metrics.prom
  
    extra_labels:
      node: !Env HOSTNAME
    event_names:
      - task_cycles # do not remove: USED BY E2E tests
      - task_instructions
      - task_cache_references
      - task_cache_misses
    wss_reset_cycles: 20
    wss_membw_threshold: 0.01
    wss_stable_cycles: -5
    rdt_enabled: true
  
  # TODO: configure
  allocator: !DicerAllocator
    appname_hp: "memcached-server"
    appname_be: "parsec"
    prom_host: "http://172.17.0.5"
    prom_port: 9090
    bw_limit: 5056506521600
    qos_metric: 'memcached_metrics{metric="95th"}'
    phase_threshold: 0.2
    max_ways_available: 6
    config: "/etc/wca/static_allocation.yaml"
    min_cache_ways_limit: 2

  # allocator: !StaticAllocator
    # config: "/etc/wca/static_allocation.yaml"

  allocations_storage: !LogStorage
    output_filename: allocations.logs

  anomalies_storage: !LogStorage
    output_filename: anomalies.logs
