- name: default-allocation
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"

- name: memcached-server
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-9"
    rdt:
      name: "memcached-server-rdt"
      l3: "L3:0=fffff"
  labels:
    app: memcached-server

- name: mazes-server
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-9"
    rdt:
      name: "mazes-server-rdt"
      l3: "L3:0=fffff"
  labels:
    app: mazes-backend

- name: nginx-server
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-9"
    rdt:
      name: "nginx-server-rdt"
      l3: "L3:0=fffff"
  labels:
    app: nginx-server

- name: parsec
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-9"
  labels:
    app: parsec
