- name: memcached-client
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
  labels:
    app: memcached-client

- name: memcached-server
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-9"
    rdt:
      name: "memcached-server-rdt"
      l3: "L3:0=fffff"
  labels:
    app: memcached-server

- name: memcached-rps-calculator
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
  labels:
    app: memcached-rps-calculator

- name: prometheus
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
  labels:
    name: "prometheus"

- name: prometheus-operator
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
  labels:
    name: "prometheus-operator"

- name: grafana
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
  labels:
    name: grafana

- name: wca
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
  labels:
    name: wca
