- name: default-allocation
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"

- name: memcached-server
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-3"
    rdt:
      name: "memcached-server-rdt"
      l3: "L3:0=000ff"
  labels:
    app: memcached-server

- name: mazes-server
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-9"
    rdt:
      name: "mazes-server-rdt"
      l3: "L3:0=fffff"
  labels:
    app: mazes-backend

- name: highpriority
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-3"
    rdt:
      name: "highpriority"
      l3: "L3:0=0000f"
  labels:
    clos: highpriority

- name: besteffort
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "4-9"
    rdt:
      name: "besteffort"
      l3: "L3:0=000f0"
  labels:
    clos: besteffort
