- name: memcached-client
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
    rdt:
      name: "memcached-client-rdt"
      l3: "L3:1=fffff"
  labels:
    app: memcached-client

- name: memcached-server
  allocations:
    cpuset_mems: "0"
    cpuset_cpus: "0-9"
    rdt:
      name: "memcached-server-rdt"
      l3: "L3:0=ffff0"
  labels:
    app: memcached-server

- name: memcached-rps-calculator
  allocations:
    cpuset_mems: "1"
    cpuset_cpus: "10-19"
  labels:
    app: memcached-rps-calculator

