version: '3.6'

services:
    server:
        image: cloudsuite3/data-caching:server
        command: "-t 4 -m 4096 -n 550"
        tty: true

    client:
        image: cloudsuite3/data-caching:client
        tty: true
        depends_on:
          - server
        volumes:
            - "~/dev/kro/benchmarks/memcached/:/usr/src/memcached/memcached_client/volumes"
        entrypoint: "tail -f /dev/null"
# /usr/src/memcached/volumes/client_entrypoint.sh && 
