apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kro

resources:
  - server.yaml
  - client.yaml
  - rps_calculator.yaml

configMapGenerator:
  - name: docker-servers
    files:
    - docker_servers.txt
