---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: memcached-rps-calculator
    labels:
        app: memcached-rps-calculator
spec:
    replicas: 1
    selector:
        matchLabels:
            app: memcached-rps-calculator
    template:
        metadata:
            name: memcached-rps-calculator
            labels:
                app: memcached-rps-calculator
        spec:
          containers:
          - name: memcached-rps-calculator
            image: aorfanou/cloudsuite-data-caching-rps-calculator:latest
            imagePullPolicy: Always
            tty: true
            args:
            - "-w 6"
            - "-S 2"
            - "-D 4096"
            - "-T 1"
            - "-s ./volumes/docker_servers.txt"
            - "-t 15s"
            - "-Q 10"
            - "-r 0.1"
            - "-j"
            - "-v"
            volumeMounts:
            - name: docker-servers
              mountPath: /usr/src/memcached/memcached_client/volumes/docker_servers.txt
              subPath: docker_servers.txt
          volumes:
          - name: docker-servers
            configMap:
              name: docker-servers
