---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: memcached-rps-calculator
    labels:
        app: memcached-rps-calculator
spec:
    replicas: 1
    selector:
        matchLabels:
            app: memcached-rps-calculator
    template:
        metadata:
            name: memcached-rps-calculator
            labels:
                app: memcached-rps-calculator
        spec:
          containers:
          - name: memcached-rps-calculator
            image: aorfanou/cloudsuite-data-caching-client:latest
            imagePullPolicy: Always
            tty: true
            args:
            - "--threads 10"
            - "--scaling_factor 30"
            - "--target_server_memory 4096"
            - "--statistics_interval 1"
            - "--server_config ./volumes/docker_servers.txt"
            - "--timeout 2m"
            - "--QOS 5"
            - "--rps_reduction_factor 0.1"
            - "--warmup_server"
            - "--calculate_rps"
            - "-v"
            volumeMounts:
            - name: docker-servers
              mountPath: /usr/src/memcached/memcached_client/volumes/docker_servers.txt
              subPath: docker_servers.txt
          volumes:
          - name: docker-servers
            configMap:
              name: docker-servers
