{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "benchmark_request_processing_seconds"
    }
   ]
  },
  {
   "title": "Query type count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "benchmark_query_type_count_total"
    }
   ]
  },
  {
   "title": "CPU Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(task_cpu_usage_seconds[5m])"
    }
   ]
  }
 ]
}