---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: memcached-client
    labels:
        app: memcached-client
spec:
    replicas: 1
    selector:
        matchLabels:
            app: memcached-client
    template:
        metadata:
            name: memcached-client
            labels:
                app: memcached-client
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8001"
        spec:
          containers:
          - name: memcached-client
            image: aorfanou/cloudsuite-data-caching-client:latest
            imagePullPolicy: Always
            tty: true
            args:
            - "--threads 10"
            - "--scaling_factor 30"
            - "--target_server_memory 4096"
            - "--statistics_interval 1"
            - "--server_config ./volumes/docker_servers.txt"
            - "--timeout 1m"
            - "--QOS 10"
            - "--rps_reduction_factor 0.1"
            - "--warmup_server"
            - "--prom_server_port 8001"
            - "--rps 290000"
            - "-v"
            ports:
            - containerPort: 8001
              protocol: TCP
            volumeMounts:
            - name: docker-servers
              mountPath: /usr/src/memcached/memcached_client/volumes/docker_servers.txt
              subPath: docker_servers.txt
          volumes:
          - name: docker-servers
            configMap:
              name: docker-servers
