apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached-client
  labels:
    team: monitoring
spec:
  selector:
    matchLabels:
      name: memcached-client
  endpoints:
  - port: memcached-client-metrics
    interval: 10s
    # https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#relabelconfig
    # https://github.com/grafana/kubernetes-app/issues/31#issuecomment-409862549
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      action: replace
      targetLabel: nodename

