apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wca
  labels:
    name: wca
spec:
  selector:
    matchLabels:
      name: wca
  template:
    metadata:
      labels:
        name: wca
      annotations:
        prometheus.io/scrape: "true"
        # Retrieves the metics from the node-exporter port on the daemonset pods
        prometheus.io/port: "9100"
    spec:
      # Uncomment and apply the wca monitoring label in the targeted nodes
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: monitoring
      #           operator: In
      #           values:
      #           - wca
      priorityClassName: high-priority
      terminationGracePeriodSeconds: 1
      hostPID: true
      hostIPC: true
      hostNetwork: true
      serviceAccountName: wca
      containers:

      - name: wca
        imagePullPolicy: Always # for debugging purpose and stream the development!
        image: wca
        securityContext:
          privileged: true
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        volumeMounts:
          - name: var-lib-wca
            mountPath: /var/lib/wca/
          - name: cgroup
            mountPath: /sys/fs/cgroup/
          # KRO TODO: uncomment
          # error: read only filesystem
          # - name: resctrl
          #   mountPath: /sys/fs/resctrl/
          - name: dev-cpu
            mountPath: /dev/cpu
          - name: allocator-config
            mountPath: /etc/wca/allocator_config.yaml
            subPath: allocator_config.yaml
            readOnly: true
          - name: static-allocation-config
            mountPath: /etc/wca/static_allocation.yaml
            subPath: static_allocation.yaml
            readOnly: true
          - name: proc
            mountPath: /proc
          - name: devices
            mountPath: /sys/devices
        # Use default entrypoint that is different for
        # devel and standalone based images.
        # command:
        #   - /usr/bin/wca.pex
        args:
        - "--config=/etc/wca/allocator_config.yaml"
        - "--register=extra.cache_way_rotation_allocator:CacheWayRotationAllocator"
        - "--log=debug"
        - "--root"
        resources:
          requests:
            cpu: 500m

      - name: node-exporter
        image: prom/node-exporter:v0.18.1
        securityContext:
          privileged: true
        args:
          - --collector.textfile.directory
          - /var/lib/wca
        ports:
          - containerPort: 9100
            protocol: TCP
        volumeMounts:
          - name: var-lib-wca
            mountPath: /var/lib/wca
          - name: dev
            mountPath: /host/dev
          - name: proc
            mountPath: /host/proc
          - name: sys
            mountPath: /host/sys
          - name: rootfs
            mountPath: /rootfs
        resources:
          requests:
            cpu: 500m

      volumes:
        - name: allocator-config
          configMap:
            name: allocator-config
        - name: static-allocation-config
          configMap:
            name: static-allocation-config
        # Volume to write wca log
        - name: var-lib-wca
          emptyDir: {}
        # Path for wca to read cgroup, resctrl and dev-cpu
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup/
        # KRO TODO: uncomment
        # - name: resctrl
        #   hostPath:
        #     path: /sys/fs/resctrl/
        - name: dev-cpu
          hostPath:
            path: /dev/cpu
        - name: devices
          hostPath:
            path: /sys/devices

        # Paths for nodeexporter to collect metrics
        - name: proc
          hostPath:
            path: /proc
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /
