kind: Service
apiVersion: v1
metadata:
  name: wca
  namespace: wca
  labels:
    name: wca
spec:
  type: ClusterIP
  selector:
    name: wca
  ports:
    - name: web
      port: 9100
      targetPort: 9100
