apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  version: v2.12.0
  evaluationInterval: 1s
  retention: 60d
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
      matchExpressions: []
  serviceMonitorSelector:
      matchExpressions: []
  podMonitorNamespaceSelector:
      matchExpressions: []
  podMonitorSelector:
      matchExpressions: []
  ruleSelector:
      matchExpressions: []
  ruleNamespaceSelector:
      matchExpressions: []
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
  # Node binding to master
  tolerations:
    - key: master
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/master: ""
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: manual
        resources:
          requests:
            storage: 10Gi

