version: '3.6'

services:
    server:
        image: cloudsuite3/data-caching:server
        command: "-t 4 -m 2048 -n 550"
        tty: true

    # client_rps_calculator:
    #   build: ./client
    #   tty: true
    #   command:
    #   - "--threads 4"
    #   - "--scaling_factor 2"
    #   - "--target_server_memory 2048"
    #   - "--statistics_interval 1"
    #   - "--server_config ./docker_servers.txt"
    #   - "--timeout 15s"
    #   - "--QOS 10"
    #   - "--rps_reduction_factor 0.1"
    #   - "--warmup_server"
    #   - "--calculate_rps"
    #   - "-v"
    #   depends_on:
    #     - server
    #   volumes:
    #     - "~/dev/kro/docker/benchmarks/memcached/docker_servers.txt:/usr/src/memcached/memcached_client/docker_servers.txt"
    #     - "~/dev/kro/docker/benchmarks/memcached/client/entrypoint.py:/usr/src/memcached/memcached_client/entrypoint.py"
    #     - "~/dev/kro/docker/benchmarks/memcached/client/entrypoint.sh:/usr/src/memcached/memcached_client/entrypoint.sh"

    client:
      build: ./client
      tty: true
      command:
      - "--threads 4"
      - "--scaling_factor 2"
      - "--target_server_memory 2048"
      - "--statistics_interval 1"
      - "--server_config ./docker_servers.txt"
      - "--timeout 15s"
      - "--QOS 10"
      - "--rps_reduction_factor 0.1"
      - "--warmup_server"
      - "--prom_server_port 8001"
      - "--rps 50000"
      - "-v"
      depends_on:
        - server
      volumes:
        - "~/dev/kro/docker/benchmarks/memcached/docker_servers.txt:/usr/src/memcached/memcached_client/docker_servers.txt"
      ports:
      - 8001:8001
