version: '3.6'

services:
    server:
        image: cloudsuite3/data-caching:server
        command: "-t 4 -m 4096 -n 550"
        tty: true

    client_rps_calculator:
      build: ./client_rps_calculator
      tty: true
      command:
      - "-w 6"
      - "-S 2"
      - "-D 4096"
      - "-T 1"
      - "-s ./docker_servers.txt"
      - "-t 15s"
      - "-Q 10"
      - "-r 0.1"
      - "-j"
      - "-v"
      depends_on:
        - server
      volumes:
        - "~/dev/kro/docker/benchmarks/memcached/docker_servers.txt:/usr/src/memcached/memcached_client/docker_servers.txt"

    client:
      build: ./client
      tty: true
      command:
      - "-w 6"
      - "-S 2"
      - "-D 4096"
      - "-T 1"
      - "-s docker_servers.txt"
      - "-g 0.8"
      - "-c 200"
      - "-r 50000"
      depends_on:
        - server
      volumes:
        - "~/dev/kro/docker/benchmarks/memcached/docker_servers.txt:/usr/src/memcached/memcached_client/docker_servers.txt"
